config/routes.rb
Rails.application.routes.draw do
  resources :concerts do
    resources :comments
  end

  get '/' => 'site#home'
end


# concert_poster


# Calendar
# concert_id
# city_id






# COMMENTS  concerts with comments (form name and comment)
# user, comment, concert_id




# CITIES AVAILABLE
# Home with:
# today concerts
# sidebar future concerts (link to future concerts)
# Other page
# 1)select concerts by price range 
# 2)Popular concerts (ordered by number of comments)

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	has_many :comments, dependent: :delete_all

	validates :band, presence: true
	validates :description, presence: true, length: { in: 10..300 }
	validates :city, presence: true
	validates :venue, presence: true
	validates :date, presence: true
	validates :price, presence: true, numericality: true


	def self.actual_month
		from = Time.now.in_time_zone.beginning_of_month
		to = Time.now.in_time_zone.end_of_month
		where(date: from..to)
	end

	def self.top_commented
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_current_month_concerts

  private
  def set_current_month_concerts
  	@current_month_concerts = Concert.actual_month
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def new
		@concert = Concert.find params[:concert_id]
		@comment = @concert.comments.new
	end

	def create
		@concert = Concert.find params[:concert_id]
		@comment = @concert.comments.new comment_params
		if @comment.save
			redirect_to concert_path(@concert.id)
		else
			render 'new'
		end
	end

	def destroy
	end

	private
	def comment_params
		params.require(:comment).permit(:username, :comment)
	end


end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

def index
	# @pop_concerts = Concert.popular
	# @month_concerts = Concert.this_month(actual_month)
	@concerts = Concert.all
	@top_comments_concerts = Concert.top_commented
end

def show
	@concert = Concert.find params[:id]
end

def new
	@concert = Concert.new
end

def create
	@concert = Concert.new concert_params
	if @concert.save
		redirect_to concert_path(@concert.id)
	else
		render 'new'
	end
end

def edit
	@concert = Concert.find params[:id]
	render 'new'
end

def update
	@concert = Concert.find params[:id]
		@concert.update_attributes concert_params
		if @concert.save
			redirect_to concert_path(@concert.id)
		else
			render 'new'
		end
end

def destroy
end

private
def concert_params
	params.require(:concert).permit(:band, :description, :city, :venue, :date, :price)
end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
def home
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/comments/_form.html.erb
<%= form_for [@concert, @comment] do |f| %>
	<fieldset>
		<legend>New concert</legend>
		<div class="text">
			<%= f.label :username %>
			<%= f.text_field :username, placeholder: "Your username" %>
		</div>
		<div class="textarea">
			<%= f.label :comment %> <br>
			<%= f.text_area :comment, placeholder: "Comment here", id: "textarea" %>
		</div>
		<%= f.submit 'Add comment' %>
	</fieldset>
<% end %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/concerts/_form.html.erb
<%= form_for [@concert] do |f| %>
	<fieldset>
		<legend>New concert</legend>
		<div class="text">
			<%= f.label :band %> <br>
			<%= f.text_field :band, placeholder: "Band name" %>
		</div>
		<div class="textarea">
			<%= f.label :description %> <br>
			<%= f.text_area :description, placeholder: "Description", id: "textarea" %>
		</div>
		<div class="text">
			<%= f.label :city %>
			<%= f.text_field :city %>
			
			<%= f.label :venue %>
			<%= f.text_field :venue %>
		</div>
		<div class="text">
			<%= f.label :date %>
			<%= f.date_field :date %>

			<%= f.label :price %>
			<%= f.number_field :price, placeholder: "Ticket Price" %>
		</div>
		<%= f.submit 'Add concert' %>
	</fieldset>
<% end %>

app/views/concerts/index.html.erb
<h2>All concerts</h2>

<div class="row">
	<article class="content--listed">
		<table class="table">
			<thead>
				<tr>
					<th>Concert</th>
					<th>City</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				<% @concerts.each do |concert| %>
					<tr>
						<td><%= concert.band %></td>
						<td><%= concert.city %></td>
						<td><%= concert.date %></td>
						<td><%= link_to("Read more...", concert_path(concert.id)) %></td>
					</tr>
				<% end %>	
			</tbody>
		</table>
	</article>
</div>


<aside class="options">
	<span><%= link_to("Add new concert to the calendar", new_concert_path, class:"btn btn-primary btn-lg") %></span>
</aside>

app/views/concerts/new.html.erb
<h4>Add your concert</h4>
<p>Please fill the form, all fields are required</p>

<%= render 'form' %>

app/views/concerts/show.html.erb
<div class="media">
  <div class="media-left media-top">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= @concert.band %></h4>
		<p>
			<%= @concert.description %>
		</p>
    <p>
    	Location: <span><%= @concert.city %></span> - <span><%= @concert.venue %></span>
    	<br>
	    <span class="concert__date"> <%= @concert.date %></span>
	    <br>
	    <span>Price: <%= @concert.price %>€</span>
    </p>
    <p>
      <%= link_to("Edit", edit_concert_path(@concert.id), class: "btn btn-primary", role: "group") %>
      <%= link_to("Add Comment", new_concert_comment_path(@concert.id), class: "btn btn-warning", role: "group") %>
    </p>
  </div>
</div>

<% @concert.comments.each do |comment| %>
  <li><%= comment.username %></li>
  <li><%= comment.comment %></li>
<% end %>






<aside class="options">
	<span><%= link_to("Back to concerts", concerts_path) %></span>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>MusicConcertNetwork</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>



 <!--************* $NAV *************-->

	<nav class="navbar navbar-default navbar--top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>

				<%= link_to(concerts_path, class: "nav--link") do
					image_tag "/images/logo.png"
				end %>

	      <a class="navbar-brand" href="#"><%= image_tag '' %></a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
	      <ul class="nav navbar-nav navbar--top__list">
	        <li class="active"><%= link_to("Concerts", concerts_path, class: "nav--link") %></li>
	        <li class="active"><%= link_to("Cities", concerts_path, class: "nav--link") %></li>
	        <li class="active"><%= link_to("Whatever", concerts_path, class: "nav--link") %></li>
	      </ul>  
     	 	<p class="navbar-text navbar-right">Signed in as <strong>Invited</strong></p>
    	</div>
		</div>
	</nav>

<!--************* $HEADER *************-->




<!--************* $MAIN CONTENT *************-->
	
	
	<div class="container">
		<div class="row">
			<section class="col-sm-8 main-content">
				<%= yield %>
			</section>

			<!--************* $SIDEBAR *************-->
			<aside class="col-sm-4 lateral-info--right">
				<%= render 'shared/sidebar' %>
			</aside>
		</div>
	</div>

	
	
	

	</body>
</html>

app/views/shared/_sidebar.html.erb
<h3>Current month</h3>

<table class="table">
	<% @current_month_concerts.each do |current_concert| %>
		<thead>
			<tr>
				<th><%= link_to(current_concert.band, concert_path(current_concert.id))%></th>
			</tr>
		</thead>
		<tbody>
			<td><%= current_concert.city %></td>
			<td><%= current_concert.date %></td>
		</tbody>

	<% end %>
</table>

app/views/site/home.html.erb
<h3>Concerts Calendar</h3>